(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"HB_Display_Stanwood_160x600_atlas_1", frames: [[0,0,550,1200]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._160x600_Stanwood_r2 = function() {
	this.initialize(ss["HB_Display_Stanwood_160x600_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.QUOTEbox = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5C9137").s().p("AvnEsIAApXIcHAAQDIAAAADIIAAGPg");
	this.shape.setTransform(100,30);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.QUOTEbox, new cjs.Rectangle(0,0,200,60), null);


(lib.quote = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// quote
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAANIAKgaIALAAIgNAagAgUANIAMgaIAJAAIgMAag");
	this.shape.setTransform(14.225,10.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgFAFQgCgCABgDQAAgCADgCQACgCACAAQADAAACACQACACgBACQAAADgDACQgCACgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBg");
	this.shape_1.setTransform(9.075,16.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAgQgDgBgCgDIgBgFIABgHIAEgaIgMAAIACgIIALAAIACgPIAJAAIgCAPIAPAAIgCAIIgOAAIgDAXIAAAEIAAAEIABADIAEABIAEgBIAEgBIgBAJIgDABIgDABIgCAAIgCAAQgEAAgDgCg");
	this.shape_2.setTransform(5.85,13.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgOAaIgGgDIgDgFQgBgDABgDQAAgGADgDQADgDAEgCIAKgCIAKgBIAHAAIABgDIgBgDIgBgEIgEgDIgFgBIgEABIgFABIgDADIgDACIgFgHQAFgEAFgBQAGgDAFAAQAFAAAEACQAEABADADQACACABAEIAAAGIgEAZIAAAGIgBAEIgIAAIAAgEIAAgEQgEAFgFACQgEACgFAAIgHgBgAABACQgDAAgDABQgEABgCACQgCACAAADQgBAEADACQACACAGABQADAAADgCIAFgEQACgBABgEIACgFIAAgDIgFAAg");
	this.shape_3.setTransform(0.8042,14.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AALAqIAEggIAAgFIgCgFQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgEAAIgFAAIgFACIgEAGIgCAIIgEAbIgKAAIAMhSIAKAAIgGAnQADgFAFgDQAEgCAGAAIAHABIAGAEQACACABAEQABADgBAFIgFAig");
	this.shape_4.setTransform(-5.0917,12.75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgFAgQgEgBgBgDIgBgFIABgHIAEgaIgMAAIABgIIAMAAIACgPIAJAAIgCAPIAOAAIgBAIIgOAAIgDAXIAAAEIAAAEIABADIAEABIAEgBIAEgBIgBAJIgDABIgDABIgCAAIgCAAQgEAAgDgCg");
	this.shape_5.setTransform(-10,13.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOAZQgEgCgEgFIAJgGIAFAEQADACAEAAQADAAADgCQAEgBABgDIgBgEIgEgDIgEAAIgCgBIgGgCIgFgCIgDgEQAAgDAAgEQABgDABgEIAGgEIAHgEIAGgBQAFAAAFADQAEABACAFIgIAGIgEgEIgGgBIgFABQgDACgBADIABADIAEADIADABIAEABIAFABIAFACQACADAAACQACADgBADQgBAEgCADQgCAEgEABIgHADIgHABQgGAAgFgCg");
	this.shape_6.setTransform(-17.7,14.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFAgQgDgBgCgDIgBgFIABgHIAEgaIgLAAIABgIIALAAIACgPIAJAAIgCAPIAPAAIgCAIIgOAAIgDAXIAAAEIAAAEIABADIAEABIAEgBIADgBIAAAJIgDABIgDABIgCAAIgCAAQgEAAgDgCg");
	this.shape_7.setTransform(-21.95,13.625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgDQgDgEgBgFQgBgFABgGQABgFACgFQADgFAEgEQAEgDAGgCQAFgDAFAAQAHAAAEADQAEACADAEQACAEABAFIAAAJIAAAEIgpAAQgBADABADQABACADACIAFADIAGABQAEAAAEgCIAHgFIAGAFQgJALgOAAQgGAAgFgCgAgDgRQgDABgCADIgEAEIgCAGIAeAAIAAgHIgCgEIgEgEIgHgBIgGACg");
	this.shape_8.setTransform(-27.0825,14.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUAmQgGgCgFgFIAIgJQADAFAEABQAFADAFAAQAGAAADgCQAEgBACgDIAEgGIACgGIABgIIgBAAQgDAFgFACQgGACgEAAQgGAAgEgCQgFgCgDgEQgDgDgBgEQgCgFABgFQABgHADgEQACgGAEgDQAEgEAFgCQAGgCAFAAQAFAAAFACQAEACADAFIABgIIAKAAIgHAzQgBAGgDAFQgDAFgEAEQgEADgGACQgEACgHAAQgHAAgGgCgAgDgdIgGAEIgEAGQgCAEAAAEQgBAHAEAEQAEAFAIAAQAGAAAGgFQAFgEABgHIAAgIIgDgGIgEgEIgHAAIgHAAg");
	this.shape_9.setTransform(-33.675,15.55);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgDQgDgEgBgFQgBgFABgGQABgFACgFQADgFAEgEQAEgDAGgCQAFgDAFAAQAHAAAEADQAEACADAEQACAEABAFIAAAJIAAAEIgpAAQgBADABADIAEAEIAFADIAGABQAEAAAEgCIAHgFIAGAFQgJALgOAAQgGAAgFgCgAgDgRQgDABgCADIgEAEIgCAGIAeAAIAAgHIgCgEIgEgEIgHgBIgGACg");
	this.shape_10.setTransform(-42.9325,14.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUAmQgGgCgFgFIAIgJQADAFAEABQAFADAFAAQAGAAADgCQAEgBACgDIAEgGIACgGIABgIIgBAAQgDAFgFACQgGACgEAAQgGAAgEgCQgFgCgDgEQgDgDgBgEQgCgFABgFQABgHADgEQACgGAEgDQAEgEAFgCQAGgCAFAAQAFAAAFACQAEACADAFIABgIIAKAAIgHAzQgBAGgDAFQgDAFgEAEQgEADgGACQgEACgHAAQgHAAgGgCgAgDgdIgGAEIgEAGQgCAEAAAEQgBAHAEAEQAEAFAIAAQAGAAAGgFQAFgEABgHIAAgIIgDgGIgEgEIgHAAIgHAAg");
	this.shape_11.setTransform(-49.525,15.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgOAaIgGgDIgDgFQgBgDABgDQAAgGADgDQADgDAEgCIAKgCIAKgBIAHAAIABgDIgBgDIgBgEIgEgDIgFgBIgEABIgFABIgDADIgDACIgFgHQAFgEAFgBQAGgDAFAAQAFAAAEACQAEABADADQACACABAEIAAAGIgEAZIAAAGIgBAEIgIAAIAAgEIAAgEQgEAFgFACQgEACgFAAIgHgBgAABACQgDAAgDABQgEABgCACQgCACAAADQgBAEADACQACACAGABQADAAADgCIAFgEQACgBABgEIACgFIAAgDIgFAAg");
	this.shape_12.setTransform(-55.6458,14.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgGAgQgCgBgBgDIgBgFIAAgHIAEgaIgLAAIAAgIIAMAAIACgPIAJAAIgCAPIAOAAIgBAIIgOAAIgDAXIAAAEIAAAEIABADIAFABIADgBIADgBIgBAJIgCABIgCABIgDAAIgCAAQgFAAgDgCg");
	this.shape_13.setTransform(-60.35,13.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgaQgCgCAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCACQgDACgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAgBg");
	this.shape_14.setTransform(-63.445,13);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAbIAHgzIAKAAIgBAIQACgFAFgCQAFgDAEAAIAFABIgCALIgDgBIgCAAQgHAAgFAEQgDAEgBAIIgEAag");
	this.shape_15.setTransform(-66.825,14.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgDQgDgEgBgFQgBgFABgGQABgFACgFQADgFAEgEQAEgDAGgCQAFgDAFAAQAHAAAEADQAEACADAEQACAEABAFIAAAJIAAAEIgpAAQgBADABADIAEAEIAFADIAGABQAEAAAEgCIAHgFIAGAFQgJALgOAAQgGAAgFgCgAgDgRQgDABgCADIgEAEIgCAGIAeAAIAAgHIgCgEIgEgEIgHgBIgGACg");
	this.shape_16.setTransform(-72.1325,14.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAPAnIAFgkIgoAAIgFAkIgKAAIALhNIAKAAIgEAgIAnAAIAFggIAKAAIgLBNg");
	this.shape_17.setTransform(-79.075,13);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgFAFQgCgCABgDQAAgCADgCQACgCACAAQADAAACACQACACgBACQAAADgDACQgCACgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBg");
	this.shape_18.setTransform(18.825,2.175);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgUAmQgGgCgFgFIAIgJQADAEAEACQAFACAFABQAGAAADgCQAEgBACgDIAEgGIACgGIABgIIgBAAQgDAFgFACQgGACgEAAQgGAAgEgCQgFgCgDgDQgDgEgBgEQgCgFABgFQABgHADgEQACgGAEgDQAEgEAFgCQAGgCAFAAQAFAAAFACQAEADADAEIABgHIAKAAIgHAyQgBAGgDAFQgDAFgEAEQgEADgGACQgEACgHAAQgHAAgGgCgAgDgcIgGADIgEAGQgCADAAAFQgBAHAEAEQAEAFAIAAQAGAAAGgFQAFgEABgHIAAgIIgDgGIgEgDIgHgBIgHABg");
	this.shape_19.setTransform(14.025,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AALAbIAEgeIAAgGIgCgEQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgEAAIgFABIgFADIgEAFIgCAHIgEAbIgKAAIAHgzIAKAAIgBAIQADgFAFgCQAEgDAGAAIAHABIAGAEQACACABAEQABAEgBAFIgFAhg");
	this.shape_20.setTransform(7.7083,0.175);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_21.setTransform(3.755,-1.05);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgSAoQgFgCgDgEQgDgEgBgFQgBgEABgGQABgGACgFQADgEAEgEQAEgEAFgCQAFgCAGAAQAFAAAEADQAFACACAEIAGgmIAKAAIgMBSIgKAAIABgIIAAAAQgEAEgFADQgEACgFAAQgHAAgEgCgAgHgBIgGADIgEAFQgCAEgBAEQAAAEABADQAAADACADQACACADABQADACAEAAQAEAAACgCQAEgBACgCIAEgGQACgDABgEIAAgIIgDgFIgFgDIgGgBIgHABg");
	this.shape_22.setTransform(-0.92,-1.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgKAqIALhTIAKAAIgLBTg");
	this.shape_23.setTransform(-5.575,-1.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_24.setTransform(-8.145,-1.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgPAZQgDgBgDgCIgDgGQgBgEABgFIAEghIAKAAIgEAeIAAAGIACAEIAEADIAEAAQAFAAAFgEQAFgEABgJIAEgaIAKAAIgIAzIgJAAIABgIIgBAAQgCAEgFADQgEADgGAAIgHgCg");
	this.shape_25.setTransform(-12.6583,0.325);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgKAoQgFgDgCgEIgBAIIgKAAIALhSIAKAAIgFAmIAAAAQADgEAGgCQAEgDAFAAQAHAAAEACQAFACADAEQADAEABAEQABAFgBAGQgBAGgCAEQgDAFgEAEQgEAEgFACQgFACgFAAQgGAAgEgCgAgCgBIgGADIgFAFIgCAIIAAAHIADAGQACACADABQADACAEAAQADAAADgCQAEgBACgCIAEgGQACgDABgEQAAgEgBgEQAAgDgCgCIgFgDIgHgBIgGABg");
	this.shape_26.setTransform(-19.2167,-1.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgfAqIAMhSIAKAAIgBAIIAAAAQAEgFAFgCQAEgCAFAAQAHAAAEACQAFACADAEQADADABAFQABAFgBAGQgBAGgCAFQgDAEgEAEQgEADgFACQgFADgGAAQgFAAgEgDQgFgCgCgEIgGAmgAAAgfIgGAEIgFAGIgCAHIAAAIIADAFQACACADABQADABADAAQAEAAADgBQAEgBACgCIAEgFQACgEABgEQAAgEgBgDQAAgDgCgDIgFgEIgHgBIgGABg");
	this.shape_27.setTransform(-29.1917,1.725);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_28.setTransform(-33.295,-1.05);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AALAqIAEggIAAgFIgCgFQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgEAAIgFABIgFABIgEAGIgCAIIgEAbIgKAAIAMhTIAKAAIgGAoQADgFAFgDQAEgCAGAAIAHABIAGAEQACACABAEQABADgBAFIgFAig");
	this.shape_29.setTransform(-38.0417,-1.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgOAZQgEgCgEgFIAJgGIAFAEQADACAEAAQADAAADgCQAEgBABgDIgBgEIgEgCIgDgBIgDgBIgGgDIgFgBIgCgEQgCgDABgEQAAgEACgDIAGgEIAGgEIAHgBQAGAAAEACQAEADACAEIgIAGIgDgEIgHgBIgFABQgDACgBADIABADIAEADIADABIAEABIAFABIAFACQACACABADQAAADAAADQgBAEgCADQgCAEgDACIgIACIgHABQgGAAgFgCg");
	this.shape_30.setTransform(-43.55,0.25);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AALAbIAEgeIAAgGIgCgEQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgEAAIgFABIgFADIgEAFIgCAHIgEAbIgKAAIAHgzIAKAAIgBAIQADgFAFgCQAEgDAGAAIAHABIAGAEQACACABAEQABAEgBAFIgFAhg");
	this.shape_31.setTransform(-48.9917,0.175);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgEQgEgDgBgGQgCgFABgFQABgFADgFQADgFAEgEQAEgDAGgDQAFgCAFAAQAGAAAEACQAFADADADQAEAEABAFQACAFgBAFQgBAFgDAFQgDAGgEADQgEAEgGACQgFACgFAAQgGAAgEgCgAgEgQIgGAEIgEAFQgCAEAAADQgBAEABADQABADACADQABACAEABQADACAEAAQADAAADgCQADgBADgCIAEgGQACgDAAgEIAAgHIgDgFIgEgEIgHgBIgHABg");
	this.shape_32.setTransform(-55.175,0.25);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_33.setTransform(-59.445,-1.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgFAgQgDgBgCgDIgBgFIABgHIAEgaIgMAAIACgIIALAAIACgPIAJAAIgCAPIAPAAIgCAIIgOAAIgDAXIAAAEIAAAEIABADIAEABIAEgBIAEgBIgBAJIgDABIgDABIgCAAIgCAAQgEAAgDgCg");
	this.shape_34.setTransform(-63,-0.425);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgOAaIgGgCIgDgGQgBgCABgEQAAgGADgDQADgDAEgCIAKgCIAKgBIAHAAIABgDIgBgDIgBgEIgEgDIgFgBIgEABIgFABIgDADIgDACIgFgHQAFgDAFgDQAGgCAFAAQAFABAEABQAEABADADQACACABADIAAAHIgEAZIAAAGIgBAEIgIAAIAAgEIAAgEQgEAFgFACQgEACgFAAIgHgBgAABABQgDAAgDACQgEABgCACQgCACAAADQgBAEADACQACACAGAAQADAAADgBIAFgDQACgCABgEIACgFIAAgDIgFAAg");
	this.shape_35.setTransform(-68.0458,0.25);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgKAqIALhTIAKAAIgLBTg");
	this.shape_36.setTransform(-71.825,-1.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgEQgDgDgBgGQgBgEABgGQABgFACgFQADgFAEgEQAEgDAGgDQAFgCAFAAQAHABAEACQAEACADAEQACAEABAFIAAAJIAAAEIgpAAQgBADABADIAEAFIAFACIAGABQAEAAAEgCIAHgFIAGAFQgJALgOAAQgGAAgFgCgAgDgRQgDABgCADIgEAEIgCAGIAeAAIAAgHIgCgEIgEgEIgHgBIgGACg");
	this.shape_37.setTransform(-76.4325,0.25);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgSAbIAHgzIAKAAIgBAIQACgFAFgCQAFgDAEAAIAFABIgCALIgDgBIgCAAQgHAAgFAEQgDAEgBAIIgEAag");
	this.shape_38.setTransform(-81.075,0.175);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgFAgQgDgBgCgDIgBgFIABgHIAEgaIgMAAIACgIIALAAIACgPIAJAAIgCAPIAPAAIgCAIIgOAAIgDAXIAAAEIAAAEIABADIAEABIAEgBIAEgBIgBAJIgDABIgDABIgCAAIgCAAQgEAAgDgCg");
	this.shape_39.setTransform(17.55,-14.475);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgPAZQgDgBgDgCIgDgGQgBgEABgFIAEghIAKAAIgEAeIAAAGIACAEIAEADIAEAAQAFAAAFgEQAFgEABgJIAEgaIAKAAIgIAzIgJAAIABgIIgBAAQgCAEgFADQgEADgGAAIgHgCg");
	this.shape_40.setTransform(12.5417,-13.725);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgEQgEgDgBgGQgCgFABgFQABgFADgFQADgEAEgFQAEgDAGgDQAFgCAFAAQAGAAAEACQAFADADADQAEAFABAEQACAFgBAFQgBAFgDAFQgDAGgEADQgEAEgGACQgFADgFgBQgGABgEgDgAgEgQIgGAEIgEAFQgCAEAAADQgBAEABADQABADACADQABACAEABQADACAEAAQADAAADgCQADgBADgCIAEgGQACgDAAgEIAAgHIgDgFIgEgEIgHgBIgHABg");
	this.shape_41.setTransform(6.125,-13.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgKAoQgFgDgCgEIgBAIIgKAAIALhSIAKAAIgFAmIAAAAQADgEAGgCQAEgDAFAAQAHAAAEACQAFACADAEQADAEABAEQABAFgBAGQgBAGgCAEQgDAFgEAEQgEAEgFACQgFACgFAAQgGAAgEgCgAgCgBIgGADIgFAFIgCAIIAAAHIADAGQACACADABQADACAEAAQADAAADgCQAEgBACgCIAEgGQACgDABgEQAAgEgBgEQAAgDgCgCIgFgDIgHgBIgGABg");
	this.shape_42.setTransform(-0.5167,-15.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgOAaIgGgCIgDgGQgBgCABgFQAAgFADgDQADgDAEgBIAKgDIAKgCIAHAAIABgCIgBgDIgBgEIgEgDIgFgBIgEABIgFABIgDACIgDADIgFgHQAFgEAFgCQAGgCAFAAQAFABAEABQAEACADACQACACABADIAAAHIgEAZIAAAGIgBAEIgIAAIAAgEIAAgEQgEAFgFACQgEADgFgBIgHgBgAABABQgDAAgDACQgEABgCACQgCACAAADQgBAEADACQACACAGAAQADAAADgBIAFgDQACgDABgDIACgFIAAgDIgFAAg");
	this.shape_43.setTransform(-6.7958,-13.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgFIAIgGIAFAEQADACAEAAQADAAADgCQAEgBAAgEIgBgDIgCgCIgFgBIgCgBIgGgDIgEgBIgEgEQgBgDABgDQABgEACgEIAFgEIAGgEIAHgBQAGAAAEACQAFACACAFIgJAGIgEgEIgGgBIgFABQgDACAAADIABADIADACIADACIAEABIAGACIAEABQACACAAADQABACAAAEQAAAEgDADQgCADgEADIgHACIgGABQgHAAgEgCg");
	this.shape_44.setTransform(-15.15,-13.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_45.setTransform(-18.445,-15.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgEgFIAJgGIAFAEQACACAFAAQADAAADgCQAEgBABgEIgCgDIgDgCIgDgBIgDgBIgGgDIgFgBIgCgEQgBgDAAgDQAAgEACgEIAGgEIAGgEIAHgBQAFAAAFACQAEACACAFIgIAGIgDgEIgHgBIgFABQgDACAAADIAAADIAEACIADACIAEABIAGACIAEABQACACABADQAAACAAAEQgBAEgCADQgCADgDADIgIACIgHABQgGAAgEgCg");
	this.shape_46.setTransform(-25.65,-13.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgOAZQgEgCgEgFIAJgGIAFAEQADACAEAAQADAAADgCQAEgBABgEIgBgDIgEgCIgDgBIgDgBIgGgDIgFgBIgCgEQgCgDABgDQAAgEACgEIAGgEIAGgEIAHgBQAGAAAEACQAEACACAFIgIAGIgDgEIgHgBIgFABQgDACgBADIABADIAEACIADACIAEABIAFACIAFABQACACABADQAAACAAAEQgBAEgCADQgCADgDADIgIACIgHABQgGAAgFgCg");
	this.shape_47.setTransform(-30.5,-13.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgEQgDgDgBgGQgBgEABgGQABgFACgFQADgFAEgEQAEgEAGgCQAFgCAFAAQAHABAEACQAEADADADQACAEABAFIAAAJIAAAEIgpAAQgBADABADIAEAFIAFACIAGABQAEAAAEgCIAHgFIAGAFQgJAMgOgBQgGABgFgDgAgDgRQgDABgCADIgEAEIgCAGIAeAAIAAgHIgCgEIgEgEIgHgBIgGACg");
	this.shape_48.setTransform(-35.8325,-13.8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AALAbIAEgeIAAgGIgCgEQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgEAAIgFABIgFADIgEAFIgCAHIgEAbIgKAAIAHgzIAKAAIgBAIQADgFAFgCQAEgDAGAAIAHABIAGAEQACACABAEQABAEgBAFIgFAhg");
	this.shape_49.setTransform(-42.0417,-13.875);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgKAnIAHgzIAJAAIgHAzgAgBgZQgCgDAAgDQABgDACgCQABgCADAAQADAAACACQACACAAADQgBADgCADQgDABgDAAQAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape_50.setTransform(-45.995,-15.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgNAZQgFgCgDgFIAIgGIAFAEQACACAFAAQADAAADgCQAEgBAAgEIgBgDIgCgCIgFgBIgCgBIgGgDIgEgBIgDgEQgCgDABgDQABgEACgEIAFgEIAGgEIAHgBQAFAAAFACQAFACACAFIgJAGIgEgEIgGgBIgFABQgDACAAADIABADIADACIADACIAEABIAGACIAEABQACACAAADQACACgBAEQAAAEgDADQgCADgDADIgIACIgGABQgHAAgEgCg");
	this.shape_51.setTransform(-50.15,-13.8);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgPAZQgDgBgDgCIgDgGQgBgEABgFIAEghIAKAAIgEAeIAAAGIACAEIAEADIAEAAQAFAAAFgEQAFgEABgJIAEgaIAKAAIgIAzIgJAAIABgIIgBAAQgCAEgFADQgEADgGAAIgHgCg");
	this.shape_52.setTransform(-55.3583,-13.725);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgKAoQgFgDgCgEIgBAIIgKAAIALhSIAKAAIgFAmIAAAAQADgEAGgCQAEgDAFAAQAHAAAEACQAFACADAEQADAEABAEQABAFgBAGQgBAGgCAEQgDAFgEAEQgEAEgFACQgFACgFAAQgGAAgEgCgAgCgBIgGADIgFAFIgCAIIAAAHIADAGQACACADABQADACAEAAQADAAADgCQAEgBACgCIAEgGQACgDABgEQAAgEgBgEQAAgDgCgCIgFgDIgHgBIgGABg");
	this.shape_53.setTransform(-61.9167,-15.275);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgaAnIgEgBIADgJIAFABIAEgBIADgBIACgDIADgEIAEgIIgOgzIALAAIAJAnIAAAAIAUgnIALAAIggA+IgEAGIgEAFIgGADIgHABg");
	this.shape_54.setTransform(-71.15,-12.475);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAZAnIAJg/IgBAAIgiA/IgHAAIgRg/IgBAAIgIA/IgLAAIALhNIAKAAIAGAAIAQA6IABAAIAfg6IAGAAIAKAAIgLBNg");
	this.shape_55.setTransform(-78.575,-15.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgBAOIANgaIAJAAIgMAagAgUAOIAOgaIAIAAIgLAag");
	this.shape_56.setTransform(-86.05,-17.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// name
	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgLAfQgFgCgFgEIAGgHIAGAFQAEACAFAAQADAAADgCQADgBACgCQACgBABgEIABgEIAAgHIgBAAQgCAEgFACQgDABgEAAQgEAAgFgBIgGgFIgFgFQgCgFABgEQgBgFACgEQABgEAEgDQADgDADgCQAFgBAEgBIAHACQAFACACAEIABAAIAAgHIAIAAIAAAqQAAAFgCAEQgCADgDAEQgDADgFABQgEABgEAAQgGAAgFgBgAgEgXIgFADIgDAFIgBAGQAAAGAEADQAEAEAFAAQAGAAAFgEQADgDABgGIgBgGIgDgFIgFgDIgGgBIgEABg");
	this.shape_57.setTransform(17.9,41.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AALAWIAAgYIgBgGIgCgDIgDgCIgEAAIgDAAIgFADIgCAEIgBAGIAAAWIgIAAIAAgqIAIAAIAAAHIAAAAQACgEAEgCQADgCAFAAIAFABIAGADIACAFQACADAAAEIAAAbg");
	this.shape_58.setTransform(12.75,40.525);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgDAgIAAgqIAHAAIAAAqgAgDgVQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAg");
	this.shape_59.setTransform(9.175,39.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgLAWIAAgqIAIAAIAAAHIAAAAIACgDIACgDIAEgBIADgBIAFABIgBAIIgCAAIgCAAQgGAAgCADQgDADAAAGIAAAWg");
	this.shape_60.setTransform(6.65,40.525);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgJAWIgEgDIgEgEIgBgFQAAgFACgCQACgDADgBQADgCAFAAIAIgBIAGAAIAAgCIgBgDIgCgDIgDgCIgEgBIgEAAIgDACIgCABIgDACIgEgFQADgDAEgCIAIgBIAJABIAFADIADAEIABAGIAAAVIAAAEIABADIgIAAIAAgGQgDAEgDACQgEABgEAAIgGAAgAAAABIgEABIgEADQgBAAAAABQAAAAAAAAQgBABAAABQAAAAAAABQAAAEADABQACACAFAAIAEgBIAEgDIACgEIABgFIAAgCIgFAAg");
	this.shape_61.setTransform(2.425,40.575);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgIAVIgGgFQgEgDgBgEQgBgEgBgFQAAgEACgEQACgEADgDQADgDAEgCQAEgBADAAQAHAAADACQAEABACAEIAFAHIABAHIAAADIgiAAIABAFIADAEQADACACAAIAFABQAEAAACgBIAGgFIAGAFQgIAIgMAAQgDAAgFgBgAANgDIgBgFIgDgDIgDgDIgGgBQgBAAgDABIgEADIgDAEIgBAEIAZAAIAAAAg");
	this.shape_62.setTransform(-2.35,40.575);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AARAgIAAgdIggAAIAAAdIgJAAIAAg/IAJAAIAAAaIAgAAIAAgaIAIAAIAAA/g");
	this.shape_63.setTransform(-8.175,39.525);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgIAhIgIgFQgCgDgCgEQgCgEAAgFQAAgFACgEQACgDACgDQADgDAFgBQADgCAFAAQAEAAAEACQAEACACADIAAAAIAAgfIAIAAIAABCIgIAAIAAgFIAAAAQgCADgEABQgFACgDABQgFAAgDgCgAgFAAIgEACIgDAEIgBAGIABAGIADAFIAEADIAFABIAGgBIAEgDIADgFIABgGIgBgGIgDgEIgEgCIgGgCIgFACg");
	this.shape_64.setTransform(-16.8,39.35);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgIAVQgEgCgDgDQgDgDgCgEQgCgEAAgFQAAgEACgEQACgEADgDQADgDAEgCQAEgBAEAAQAFAAAEABQAEACADADQADADACAEQACAEAAAEQAAAFgCAEQgCAEgDADQgDADgEACQgEABgFAAQgEAAgEgBgAgFgNIgEADIgDAFIgBAFIABAGIADAFIAEADIAFABIAGgBIAEgDIADgFIABgGIgBgFIgDgFIgEgDIgGgBIgFABg");
	this.shape_65.setTransform(-22.075,40.575);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgIAVQgEgCgDgDQgDgDgCgEQgCgEAAgFQAAgEACgEQACgEADgDQADgDAEgCQAEgBAEAAQAFAAAEABQAEACADADQADADACAEQACAEAAAEQAAAFgCAEQgCAEgDADQgDADgEACQgEABgFAAQgEAAgEgBgAgFgNIgEADIgDAFIgBAFIABAGIADAFIAEADIAFABIAGgBIAEgDIADgFIABgGIgBgFIgDgFIgEgDIgGgBIgFABg");
	this.shape_66.setTransform(-27.375,40.575);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AALAVIgLgfIgKAfIgIAAIgOgpIAJAAIAJAeIABAAIAKgeIAHAAIALAeIAKgeIAIAAIgOApg");
	this.shape_67.setTransform(-33.425,40.575);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AALAWIAAgYIgBgGIgCgDIgDgCIgEAAIgDAAIgFADIgCAEIgBAGIAAAWIgIAAIAAgqIAIAAIAAAHIAAAAQACgEAEgCQADgCAFAAIAFABIAGADIACAFQACADAAAEIAAAbg");
	this.shape_68.setTransform(-39.35,40.525);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgJAWIgEgDIgEgEIgBgFQAAgFACgCQACgDADgBQADgCAFAAIAIgBIAGAAIAAgCIgBgDIgCgDIgDgCIgEgBIgEAAIgDACIgCABIgDACIgEgFQADgDAEgCIAIgBIAJABIAFADIADAEIABAGIAAAVIAAAEIABADIgIAAIAAgGQgDAEgDACQgEABgEAAIgGAAgAAAABIgEABIgEADQgBAAAAABQAAAAAAAAQgBABAAABQAAAAAAABQAAAEADABQACACAFAAIAEgBIAEgDIACgEIABgFIAAgCIgFAAg");
	this.shape_69.setTransform(-44.225,40.575);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AAAAbIgDgEQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIAAgGIAAgVIgKAAIAAgHIAKAAIAAgMIAHAAIAAAMIALAAIAAAHIgLAAIAAASIAAAEIAAADIACACIAEABIADAAIADgBIAAAHIgEABIgEABIgHgBg");
	this.shape_70.setTransform(-48.325,40.025);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgMAgQgFgCgDgFIAHgHQACAEAEACQADACAEgBIAEAAIAEgCIADgDQAAgBAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgEgCgCIgGgDIgHgCQgEgBgDgDQgEgBgCgDQgCgFAAgFIABgHIAEgFQACgDAEgBQAEgCAFAAIAKABQAFABAEAFIgHAGIgFgDQgDgCgEAAIgFABIgEACIgCADIAAAEQAAADACACQACADAEABIAHACIAHADQAEABACAEQACADAAAGQAAAFgCADQgBAEgDADIgHAEIgIAAQgGAAgGgBg");
	this.shape_71.setTransform(-52.375,39.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AgGALIAGgVIAHAAIgHAVg");
	this.shape_72.setTransform(6.325,30.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgDAiIAAhDIAHAAIAABDg");
	this.shape_73.setTransform(4.1,27);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AgDAgIAAgpIAHAAIAAApgAgDgVQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBg");
	this.shape_74.setTransform(1.925,27.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgJAWIgEgDIgEgEIgBgFQAAgFACgCQACgDADgBQADgCAFAAIAIgBIAGAAIAAgCIgBgDIgCgDIgDgCIgEgBIgEAAIgDACIgCABIgDACIgEgFQADgDAEgCIAIgBIAJABIAFADIADAEIABAGIAAAVIAAAEIABADIgIAAIAAgGQgDAEgDACQgEABgEAAIgGAAgAAAABIgEABIgEADQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADABQACACAFAAIAEgBIAEgDIACgEIABgFIAAgCIgFAAg");
	this.shape_75.setTransform(-1.525,28.275);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AALAiIAAgZIgBgFIgCgDIgDgCIgEAAIgEAAIgDACIgDAEIgBAHIAAAWIgIAAIAAhDIAIAAIAAAgIAAAAQACgDAEgCQAEgCAEgBIAGABIAEADIADAFQACACAAAEIAAAcg");
	this.shape_76.setTransform(-6.3,27);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgVAgIAAg/IAWAAQAGAAAEACQAEABADADIADAGIAAAGIAAAGIgDAGQgDABgEACQgEACgGAAIgNAAIAAAcgAgMgDIALAAIAEAAIAFgCIADgDQABgCAAgDQAAgDgBgCIgDgEIgFgBIgEAAIgLAAg");
	this.shape_77.setTransform(-11.15,27.225);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgFAVQgEgCgDgDIgFgHQgBgEgBgFQABgEABgEIAFgHQACgDAEgCQAFgBAEAAIAJABQAEACADADIgGAGIgFgEIgGgBIgEABIgFAEIgCAFIgBAEIABAGIADAFIAFADIAEABIAGgBIAFgEIAFAGQgDADgFACQgEABgEAAQgEAAgEgBg");
	this.shape_78.setTransform(-16.05,28.275);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgJAWIgEgDIgEgEIgBgFQAAgFACgCQACgDADgBQADgCAFAAIAIgBIAGAAIAAgCIgBgDIgCgDIgDgCIgEgBIgEAAIgDACIgCABIgDACIgEgFQADgDAEgCIAIgBIAJABIAFADIADAEIABAGIAAAVIAAAEIABADIgIAAIAAgGQgDAEgDACQgEABgEAAIgGAAgAAAABIgEABIgEADQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADABQACACAFAAIAEgBIAEgDIACgEIABgFIAAgCIgFAAg");
	this.shape_79.setTransform(-20.775,28.275);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AAZAgIAAg0IgBAAIgVA0IgFAAIgVg0IgBAAIAAA0IgIAAIAAg/IANAAIATAvIAAAAIAUgvIANAAIAAA/g");
	this.shape_80.setTransform(-27.125,27.225);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgJAWIgEgDIgEgEIgBgFQAAgFACgCQACgDADgBQADgCAFAAIAIgBIAGAAIAAgCIgBgDIgCgDIgDgCIgEgBIgEAAIgDACIgCABIgDACIgEgFQADgDAEgCIAIgBIAJABIAFADIADAEIABAGIAAAVIAAAEIABADIgIAAIAAgGQgDAEgDACQgEABgEAAIgGAAgAAAABIgEABIgEADQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADABQACACAFAAIAEgBIAEgDIACgEIABgFIAAgCIgFAAg");
	this.shape_81.setTransform(-36.075,28.275);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgDAgIAAgpIAHAAIAAApgAgDgVQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBg");
	this.shape_82.setTransform(-39.425,27.2);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AALAWIAAgYIgBgGIgCgDIgDgCIgEAAIgEAAIgDADIgDAEIgBAGIAAAWIgIAAIAAgqIAIAAIAAAHIABAAQABgEADgCQAEgCAEAAIAHABIAEADIAEAFQABADAAAEIAAAbg");
	this.shape_83.setTransform(-43,28.225);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgIAVQgEgCgDgDQgDgDgCgEQgCgEAAgFQAAgEACgEQACgEADgDQADgDAEgCQAEgBAEAAQAFAAAEABQAEACADADQADADACAEQACAEAAAEQAAAFgCAEQgCAEgDADQgDADgEACQgEABgFAAQgEAAgEgBgAgFgNIgEADIgDAFIgBAFIABAGIADAFIAEADIAFABIAGgBIAEgDIADgFIABgGIgBgFIgDgFIgEgDIgGgBIgFABg");
	this.shape_84.setTransform(-48.125,28.275);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AgDAgIAAg3IgVAAIAAgIIAxAAIAAAIIgVAAIAAA3g");
	this.shape_85.setTransform(-52.375,27.225);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgsADIAAgGIBZAAIAAAGg");
	this.shape_86.setTransform(-61.95,28.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.quote, new cjs.Rectangle(-91.8,-24.2,129.4,72.2), null);


(lib.PIC = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib._160x600_Stanwood_r2();
	this.instance.setTransform(-237,-125,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.PIC, new cjs.Rectangle(-237,-125,275,600), null);


(lib.Heritage_Vert_2c_RGBeps = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Heritage_Vert_2c_RGB.eps
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14509B").s().p("AoVIWIAAwrIQrAAIAAQrgABAA4IgFADQgEADgDAGIgMAaIgOBTQgCAGACAGIAOArIADAMIAICBIAKBbIEgAcICPAAIAAnbIgDgDQgDgFgFABIgHABQgFABgFgCIgHgEQgFgCAAAFQgBAGAEADIAGAGQAEAEgFADIgGACQgEADABAFIABABIAFAWIACAEQADAGgFAAIgLgEQgFAAgEgEIgCgDQgEgEgFABIgqAJQgFABgDAFIgLASQgEAFgFABIgLABQgGABAAgHIAAgEQAAgGgFABIgXAFQgGABABAGIABANQABAHgGABIgNACQgFABgDAGIgFANQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABIgEgBIgKgGQgFgDACgGIABgCQACgGgDgFIgFgLQgDgGgFACIgJAEQgGACgFgBIgFgBQgFgCAAgGIABgQQAAgGgFACIgEABQgEABgEAFIgEAEQgEAFAEAEIAMARQADAFgFAAIgIAAQgGAAgDAFIgCADQgDAEgGABIgLABQgFAAADgFIACgDQADgFgCgDQgCgDgFAAIgNABQgFABgFgDIgDgCQgFgDADgGIADgHQACgFgFgBIgUgDQgFgBgBAGIgBAHQgBAGgFABIgDABQgFABAAgGIAAgRQAAgHgEAFIgFAGQgDAFgEgCQgEgBAAgHIAAgWQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAIgBAAIgCAAgAnrHsICoAAIDyggIAJgRIAEgMIAPhHQACgFAAgHIgChfQAAgHgCgFIgKglQgDgFAAgGIAAgJQAAgGgFgEIgdgfQgFgEgCgGIgMgdQgBgEgFgGIgOgTQgEgFgFgBIgYgDQgGgBgDgEIgMgNQgEgDgFgBIgqgCQgFAAgEAFIgGAHQgEAFgFAAIgQABIgTgCQgGgBgEACIgIAFQgFACAEAEIAGAGQAEADAAAHIAAAGQAAAGgFAAIgRgCQgFAAgFAEIgKAJQgDAEgGAAIgqgBQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIgBgBQABgGgFgDQgJgFgDAAQgBAAgEAHIgEAHQgCAGgGgBIgWgFQgGgBAAgGIAAgHQAAgGgFgBIgNgCIgBAAgAh3AzIASAOQAEADABAGIAAABIAMAbQADAGADAEIAVAUIAJAHIATAJQAFACACgFIAQguIANgbQACgFAAgHIAAgBQAAgGgDgEIgsgyIgugpIgJgIIgJgIQgFgDgFAAIgEgBQgBAAAAABQgBAAgBAAQAAAAAAABQAAAAAAABIAAAGQABAGgEAAQgDAAgEgFIgEgGQgDgFgGACIgMAEQgFABAAAHIAAAGQAAAGgGABIgFABQgFABgEgDIgDgCQgEgEgEAEIgVAVQgEAEgCAGIAAACQgCAGgFAAIgEAAQgGAAgCgFQgDgIgDAAQgCAAgDAEIgDAFQgCAEACAFIAFAKQADAEAGABIAlADQAFAAAEADIAGAEQAFADADAEIACABQADAEAGABIAWAEIALABIADAAIACAAQAEAAAEADgACfAjIAJAGIACABIAIAGQAEACADgFIAIgOQADgFgGAAIgOgBQgFAAgCgFIgFgMQgCgGgFgCQgFgCgEABIgNACQgFABgBgFIgDgPQgBgGgDgEIgJgLQgDgEgEAEIgEAEQgDAEgFgCIgJgEQgDgCgGABQgFACgBAGIgDAZQAAAFgDAGIgHAQQgCAFABAGQABAHAEgDIAHgEQAEgCAGAAIANAAIAKAAIADgBIAogFQACAAANAKgAhShdIgHANQgCAFACAFIAEAFQADAFADAAQAFABAHAGIAdAZQAFAFAEAAIADABQAFABADAGIAIANIAHAIIAMAKQAFAEAFAAIAGABQAFABADgGIAFgKIADgLIACgYIgDgZQAAgEgEgHIgCgEQgDgFgFgDQgGgEgGACIgPACIgPABQgFAAgEAEIgEADQgFAEgEAAIgLgBIgKgGQgFgEgDgDIgBgBQgEgEgBgGIAAgCQgBgGgDAAQgCAAgDAFgAnBgwIABAFQABAGAFgCIALgFQAFgBgCgGQgCgFACgFIAIgOQADgGgEgEQgEgEAEgEIAKgKQAEgDgBgHIgBgDQgBgFADgGIADgHIABgEQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgEAAIgKACIgMAFQgFACgDgFIgCgEQgDgEgEAEIgDAFQgEAFgFgCQgDgHgDgDQgCgBACgGIACgFQABgCgFgCIgGgDIgGgHQgDgEgGABIgBAAIAACBQAJgEAbgHIACAAQADAAABAFgAGqizIAEACIAKAEIAOACQAGABABAGIADAMQACAGAFAAIASgCIADABIAAlYIvXAAIAADuIADgBIALgDQAEgBAGACIAOAHQAEADAFgDIAMgJQAFgDAEACQAEADAEgEIADgDQAFgEAFABIAGAAQAFABABgHIABgEQACgHAEgBQAFgCAFACIALAEQAFACAEgEIAKgMQAEgEAFACIALAFQAGACAEgCIALgEQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQAAgBgBAAIgVgGQgFgCAAgGIgBgNQAAgGAFgBIAOgDQAFgBAAgGIAAgFQAAgGAFgBQAFgBAFACIASAFIAJAFIAKAHQAFACACgFIABgDQACgGgEgCIgBgBQgFgDgCgGIgEgKQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAIADAAIAjAFQAFABgDgFIgKgMQgEgEADgGIACgDQADgFAGgBIAYgFQAFgBgEgDIgOgNQgFgDAEgFIACgEQADgEAFACIARAHQAGACAEgDIAEgCIAKgDIAWgDIALABIAHABQAFACAAAFQAAAGAFADQAQALADgCIAEgEQAEgEADAFQAEAEAFACIARAGQAFACADgFQADgFAGAAIAGgBQAFAAADAFIACAFQADAFAFAAIAJABQAGABAEADIAdAZQAFAEAFAAIAEAAQAGAAAAgGIABgGQAAgHgFgCIgGgDQgFgCgDgFIgCgDIAAgEQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAegHQAGgBAEAEIALAJQAFADgBAHIgDATQgBAGAFACIADABQAGACAEgCIAIgFQAEgDgCgFIgGgLQgDgGAEgEIADgEQADgEAFADIANAKQAAAAABAAQAAABABAAQAAAAAAAAQABgBAAAAQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgFQABgGAEABIAaAGQAFABAFgBIAMgDQAJgBAEAJQACACgBADQAAAAAAABQgBABABAAQAAABAAAAQABABAAAAIACACQADADAAACIAAADQAAABAAAAQAAABABAAQAAABABAAQAAABABAAIADAAQADAAABADQACADgBACIgCAHIAHAHQAGAFgEAHIgCABIAAABIAAAAIgBAGQgBADgEgBQgGgBgCABQgBABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAIAAACQAAAEAEABIADABQAEABABADIACAEQACADAEgBIADgBQAEgCADACQACACABAEIABAIIABABIAIgGIADgEQAEgFgEgFIgMgQQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAJAAQAEAAAEgFIADgDQADgFAFAAIALgBQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAIgBAEIgBADQgDAFACADQABAEAGgBIAMgBQAFAAAFACIADACQAFADgCAFIgEAIQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAUADQAFAAABgFIABgIQABgGAFgBIADAAQAGgBAAAGIAAARQAAAGADgEIAFgGQAEgFADACQAEACAAAGIABAWQAAAGAEgDIADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAGALgRALIgKADIgFAEQgCADgBADIAAACQgBAHAGgBIAKgBQAHgBADgCIALgFQAFgDAFABIAZABQAGAAgBAHIgDAXQAAAGgFgCIgLgFQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIgDADIAAABQgDAFgFABIgNABQgFABABAGIADAHQACAGAFgBIAJgBIACgBQAEAAAEADg");
	this.shape.setTransform(161.525,53.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgmAnQgQgQAAgXQAAgWAQgQQAQgQAWAAQAWAAARAQQAPAQAAAWQAAAXgPAQQgRAQgWAAQgWAAgQgQg");
	this.shape_1.setTransform(150.2,149.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ABNDVQgMgMgJgbQgoAZgPAHQgmATgkAAQg7AAgiglQgggigBg0QAAgkARgaQAWggArgMIBpghQA3gTAOgPIAAgfQAAhahNAAQgcAAgUASQgXAUgOAuQgFAagZAAQgQAAgOgKQgSgNAAgTQAAgmAwgeQAzggBIAAQBYAAAkAoQAbAdAAAzIAADSQgBBEAeAGQASADAOgCIAAAXQgSAJgXAGQgYAGgWAAQgWAAgOgMgAgpAIQglAOgPASQgPATAAAfQAAAnAVAXQAVAZAmAAQAgAAAWgRQAfgXAAguIAAh8QgSAMhQAdg");
	this.shape_2.setTransform(214.65,183.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AheDcIAAgWQAmgDAIgIQAHgIAAgfIAAkYQABgXgGgGQgFgIgRgCIgagDIAAgVICJgYIAAFvQAAAeAIAIQAIAIAkADIAAAXg");
	this.shape_3.setTransform(150.15,183.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgcECQglgaAAg5IAAkuIg+AAIAAglIBCAAIA6htIAXAAIAABtIBsAAIAAAlIhsAAIAAENQAAAsARAXQAPAUAYAAQAdAAAXgJIAAAZQgzAegtAAQgjgBgZgQg");
	this.shape_4.setTransform(176.925,179);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AiVDcIAAgXQAlgDAIgIQAIgIAAgeIAAkYQAAgXgFgHQgFgHgSgCIgZgDIAAgXIB/gVIALBIQAtgqAVgOQAagRAWAAQAYAAAMAPQALAMAAARQAAAVgMAQQgNARgRAAQgKAAgIgGQgfgVgUAAQgTAAgOAUQgRAYAAAtIAADPQAAAdAIAIQAIAJAlACIAAAYg");
	this.shape_5.setTransform(120.175,183.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AiPCmQgug3AAhsQAAhmAyg8QA1hBBiAAQBpAAAsBFQAdAsAABAQAAAkgkAAIj5AAQgCBQAZAwQAgA+BIAAQAvAAAggbQAZgVAUgrIAcAPQgqB6iCAAQhpAAgyg7gAhMiGQgSAnAAAvIChAAQARAAAHgHQAGgGAAgPQAAgpgPgdQgXgugzAAQg6AAgaA6g");
	this.shape_6.setTransform(304.075,183.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AiUEoQg5gjAAg/QAAgpAlgaQAWgRAqgOIAAgCQgfgDgWgVQgWgVAAgZQAAgxBNgcIAAgCQgjgLgXgaQgfgkAAg5QAAg7AognQAvgwBeAAQAeAAAfAIQAhAHASAMIBogWIAAA6IhJAAQAMALAIAXQAIAYAAAaQAABKg5AmQgvAehIAAQgZAAgYgDQgoAOAAAZQAAAkBIAAIBPAAQCeABAAB+QAAArgWAkQgSAfgiAVQgeATgkAJQgjAIgrAAQhTAAg0gggAhiB/QgeAXAAAoQAAAwAnAdQAlAcA6AAIABAAQAzAAAigZQAkgbABgxQgBgvghgVQgfgShDgBQhEAAgbAUgAhKkNQgcAeAAA8QAAA1AaAdQAYAaAnAAQAmAAAXgbQAZgcAAg1QAAg7gbgfQgXgagjAAIgBAAQgmAAgXAag");
	this.shape_7.setTransform(259.3,194.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AiPCmQgug3AAhsQAAhmAxg8QA2hBBiAAQBpAAAsBFQAdAsAABAQAAAkglAAIj5AAQgBBQAZAwQAgA+BIAAQAvAAAggbQAZgUAUgsIAcAPQgqB6iCAAQhpAAgyg7gAhNiGQgSAnAAAvICiAAQARAAAHgHQAGgGAAgPQAAgpgPgdQgXgugzAAQg6AAgbA6g");
	this.shape_8.setTransform(81.4,183.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("ABWEvIAAgXQAogEAJgJQAIgIAAgiIAAjdIkbAAIAADdQAAAiAIAIQAJAJAoAEIAAAXIjOAAIAAgXQAogEAJgJQAHgIAAgiIAAnCQAAgigHgIQgJgJgogDIAAgXIDOAAIAAAXQgoADgJAJQgIAJAAAhIAADDIEbAAIAAjDQAAgigIgIQgJgJgogDIAAgXIDMAAIAAAXQgmADgJAJQgHAJAAAhIAAHCQAAAhAHAIQAJAKAmADIAAAYg");
	this.shape_9.setTransform(28.975,175.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#14509B").s().p("AAuB9Ihsh9IgCAAIAAB9IgsAAIAAj5IAsAAIAABsIACAAIBnhsIA8AAIh0B0IB8CFg");
	this.shape_10.setTransform(204.025,239.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#14509B").s().p("AA1B9Ih1jAIgBAAIAADAIgsAAIAAj5IA7AAIBzC6IABAAIAAi6IAsAAIAAD5g");
	this.shape_11.setTransform(174.5,239.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#14509B").s().p("ABNB9IgYg6IhrAAIgXA6IgxAAIBsj5IAmAAIBrD5gAgnAdIBNAAIgmhkg");
	this.shape_12.setTransform(146.175,239.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#14509B").s().p("AhbB9IAAj5IBgAAQAPAAANADQANADALAJQALAGAHANQAHAMAAARQAAAVgMAOQgMAOgUAFIAAABQAYAEAPANQAPAPAAAaQAAATgIAQQgIAOgNAIQgOAIgRAEQgSAEgPAAgAgvBYIA5gCQAIAAALgFQAHgDAGgIQAGgIAAgMQAAgUgOgIQgOgHgZAAIgqAAgAgvgXIAoAAQAUABANgJQALgJAAgQQAAgRgMgHQgMgHgYgBIgkAAg");
	this.shape_13.setTransform(120.775,239.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,323.1,251.9);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14509B").s().p("AASBbIgtg7IAAAAIAAA7IgdAAIAAi1IAdAAIAAByIAAAAIArgvIAlAAIgxAzIA1A/g");
	this.shape.setTransform(66.4,70.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#14509B").s().p("AghA7IAAhyIAcAAIAAATIAAAAQAFgKAHgGQAJgGAMAAIADAAIADAAIAAAbIgEgBIgFAAQgJAAgGADQgHAEgCAFQgDAFgCAFIgBAJIAAA8g");
	this.shape_1.setTransform(55.9,73.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#14509B").s().p("AgXA4QgMgEgIgIQgJgJgFgKQgFgMAAgNQAAgNAFgMQAFgKAJgJQAIgHAMgFQALgEAMAAQANAAALAEQAMAFAIAHQAJAJAFAKQAFAMAAANQAAANgFAMQgFAKgJAJQgIAIgMAEQgLAFgNAAQgMAAgLgFgAgOgiQgGAEgEAFQgEAGgCAGQgCAGAAAHQAAAGACAHQACAGAEAGQAEAFAGAEQAGADAIAAQAJAAAGgDQAGgEAEgFQAEgGACgGQACgHAAgGQAAgHgCgGQgCgGgEgGQgEgFgGgEQgGgCgJAAQgIAAgGACg");
	this.shape_2.setTransform(43.975,73.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#14509B").s().p("AAbA5IgbhPIAAAAIgZBPIgeAAIgohxIAfAAIAYBRIABAAIAZhRIAdAAIAZBRIABAAIAZhRIAdAAIgnBxg");
	this.shape_3.setTransform(27.55,73.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#14509B").s().p("AgUA4QgLgDgJgJQgIgHgFgLQgEgLAAgPQAAgNAEgLQAFgLAIgIQAIgIAMgEQALgFAMAAQAMAAAKAEQAKAEAIAHQAHAJAEALQAEAMAAAOIAAAEIAAAEIhWAAQAAAGADAFQADAGAEADQAFAEAFACQAGADAFgBQALAAAIgDQAHgFAFgGIATAPQgRAXggAAQgNAAgLgFgAAegKQAAgGgCgFQgBgFgEgEQgDgEgFgCQgFgCgHAAQgMAAgJAIQgJAHgBANIA6AAIAAAAg");
	this.shape_4.setTransform(6.025,73.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#14509B").s().p("AAbA5IgbhPIAAAAIgZBPIgdAAIgphxIAgAAIAXBRIABAAIAZhRIAeAAIAYBRIABAAIAYhRIAfAAIgpBxg");
	this.shape_5.setTransform(-9.95,73.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#14509B").s().p("AAaA5IgahPIAAAAIgZBPIgeAAIgnhxIAeAAIAYBRIABAAIAZhRIAdAAIAZBRIABAAIAZhRIAdAAIgnBxg");
	this.shape_6.setTransform(-34.2,73.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#14509B").s().p("AgXA4QgMgEgIgIQgJgJgFgKQgFgMAAgNQAAgNAFgMQAFgKAJgJQAIgHAMgFQALgEAMAAQANAAALAEQAMAFAIAHQAJAJAFAKQAFAMAAANQAAANgFAMQgFAKgJAJQgIAIgMAEQgLAFgNAAQgMAAgLgFgAgOgiQgGAEgEAFQgEAGgCAGQgCAGAAAHQAAAGACAHQACAGAEAGQAEAFAGAEQAGADAIAAQAJAAAGgDQAGgEAEgFQAEgGACgGQACgHAAgGQAAgHgCgGQgCgGgEgGQgEgFgGgEQgGgCgJAAQgIAAgGACg");
	this.shape_7.setTransform(-50.625,73.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#14509B").s().p("AAYBbIAAhAIgBgKIgCgKQgDgEgEgDQgFgCgGAAQgHAAgFACQgEACgDAFQgEAEgCAGQgBAFAAAGIAAA/IgdAAIAAi1IAdAAIAABTIAAAAIAFgHIAHgHIAKgEQAFgCAHAAQAKAAAJAEQAIAEAFAHQAFAGACAHQADAJAAAJIAABIg");
	this.shape_8.setTransform(-64.35,70.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#14509B").s().p("AgaA4QgMgFgJgJIATgSQAFAHAIADQAHAEAJABIAGgBIAGgDIAFgDQABgDAAgEQAAgIgGgCQgHgEgMgDIgNgDQgGgDgFgDQgEgDgDgGQgDgFAAgIQAAgKAEgHQAEgHAGgFQAHgEAIgCQAIgCAIAAQAMAAAMAEQAMAFAHAIIgTARQgEgFgGgEQgHgDgIAAQgGAAgGACQgGADAAAHQAAAGAHADQAGAEALACIAOAEQAGADAFADQAGADADAGQAEAGAAAJQAAAKgEAIQgEAGgHAFQgGAFgJACQgJACgJAAQgNAAgNgFg");
	this.shape_9.setTransform(54.925,47.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#14509B").s().p("AgNBWIAAhyIAbAAIAABygAgMg3QgGgGABgHQgBgGAGgGQAFgFAHAAQAIAAAFAFQAFAFABAHQgBAIgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape_10.setTransform(47.1,44.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#14509B").s().p("AASBbIgsg7IgBAAIAAA7IgcAAIAAi1IAcAAIAAByIABAAIArgvIAlAAIgzAzIA1A/g");
	this.shape_11.setTransform(33.35,43.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#14509B").s().p("AghA7IAAhyIAcAAIAAATIAAAAQAFgKAHgGQAJgGALAAIAEAAIADAAIAAAbIgEgBIgFAAQgKAAgGADQgFAEgEAFQgCAFgBAFIgBAJIAAA8g");
	this.shape_12.setTransform(22.85,46.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#14509B").s().p("AgXA5QgMgFgIgJQgJgHgFgLQgFgMAAgNQAAgNAFgMQAFgKAJgJQAIgHAMgFQALgEAMAAQANAAALAEQAMAFAIAHQAJAJAFAKQAFAMAAANQAAANgFAMQgFALgJAHQgIAJgMAFQgLAEgNAAQgMAAgLgEgAgOgiQgGAEgEAFQgEAFgCAHQgCAHAAAGQAAAGACAHQACAHAEAFQAEAFAGADQAGAEAIAAQAJAAAGgEQAGgDAEgFQAEgFACgHQACgHAAgGQAAgGgCgHQgCgHgEgFQgEgFgGgEQgGgDgJAAQgIAAgGADg");
	this.shape_13.setTransform(10.925,47.05);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#14509B").s().p("AAaA6IgahQIAAAAIgZBQIgeAAIgnhyIAeAAIAZBRIAAAAIAZhRIAdAAIAaBRIAAAAIAZhRIAdAAIgnByg");
	this.shape_14.setTransform(-5.5,47.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#14509B").s().p("AgdA3QgIgEgFgGQgGgHgCgIQgCgJAAgIIAAhHIAcAAIAAA+IABALQABAFADAFQACAEAEADQAFADAGAAQAGAAAFgDQAGgCADgFIAEgKQACgFAAgGIAAg+IAdAAIAAByIgbAAIAAgTIgBAAQgEAJgKAGQgJAHgLAAQgMAAgIgEg");
	this.shape_15.setTransform(-27.15,47.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#14509B").s().p("AgXA5QgMgFgIgJQgJgHgFgLQgFgMAAgNQAAgNAFgMQAFgKAJgJQAIgHAMgFQALgEAMAAQANAAALAEQAMAFAIAHQAJAJAFAKQAFAMAAANQAAANgFAMQgFALgJAHQgIAJgMAFQgLAEgNAAQgMAAgLgEgAgOgiQgGAEgEAFQgEAFgCAHQgCAHAAAGQAAAGACAHQACAHAEAFQAEAFAGADQAGAEAIAAQAJAAAGgEQAGgDAEgFQAEgFACgHQACgHAAgGQAAgGgCgHQgCgHgEgFQgEgFgGgEQgGgDgJAAQgIAAgGADg");
	this.shape_16.setTransform(-40.875,47.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#14509B").s().p("AgrBWIgIgBIADgZIAFABIAGAAIAIgBQACgBACgCIAFgGIADgIIAGgOIgyhyIAhAAIAeBTIABAAIAdhTIAdAAIg2CKIgHAPQgCAGgFAEQgFAEgHACQgHACgKAAg");
	this.shape_17.setTransform(-53.85,49.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#14509B").s().p("AAaA6IgahQIAAAAIgZBQIgeAAIgnhzIAeAAIAZBSIAAAAIAZhSIAeAAIAZBSIAAAAIAYhSIAfAAIgpBzg");
	this.shape_18.setTransform(64.95,20.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#14509B").s().p("AgXA5QgMgFgIgJQgJgHgFgMQgFgLAAgNQAAgNAFgLQAFgMAJgHQAIgJAMgEQALgEAMAAQANAAALAEQAMAEAIAJQAJAHAFAMQAFALAAANQAAANgFALQgFAMgJAHQgIAJgMAFQgLAEgNAAQgMAAgLgEgAgOghQgGADgEAFQgEAGgCAGQgCAHAAAGQAAAGACAHQACAGAEAGQAEAFAGADQAGAEAIAAQAJAAAGgEQAGgDAEgFQAEgGACgGQACgHAAgGQAAgGgCgHQgCgGgEgGQgEgFgGgDQgGgEgJAAQgIAAgGAEg");
	this.shape_19.setTransform(48.525,20.25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#14509B").s().p("AAYBbIAAhAIAAgKIgEgKQgCgEgEgDQgEgCgIAAQgGAAgFACQgFACgDAFQgDAEgBAGQgCAFgBAGIAAA/IgcAAIAAi1IAcAAIAABTIABAAIAFgHIAIgHIAJgEQAFgCAGAAQAMAAAHAEQAJAEAFAHQAFAGADAHQACAJAAAJIAABIg");
	this.shape_20.setTransform(34.8,16.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#14509B").s().p("AgRBXIgPgDIgPgHIgNgIIARgWQAIAIALAEQALAEALAAQAJAAAHgDQAHgDAFgFQADgGACgGQACgIAAgJIAAgIIAAAAQgGAIgKAFQgKAEgLAAQgNAAgKgEQgLgFgHgJQgIgHgEgKQgEgMAAgMQAAgMAEgLQAEgLAIgIQAGgIALgGQAKgEANAAQALAAAMAFQAKAFAGAKIABAAIAAgRIAbAAIAABoQAAAQgEANQgEAMgIAJQgIAIgMAGQgNAEgPAAgAgNg8QgGACgEAFQgEAFgCAHQgDAGAAAIQAAAHADAHQACAGAEAFQAEAEAGADQAGADAHAAQAIAAAHgDQAGgCAFgFQAEgEACgHQACgHABgHQgBgIgCgGQgCgHgEgFQgFgFgGgCQgGgEgJAAQgHAAgGAEg");
	this.shape_21.setTransform(14.8,22.95);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#14509B").s().p("AAYA7IAAg/IAAgKQgBgGgDgEQgCgFgEgCQgEgDgHAAQgGAAgFACQgFADgEAFQgDAEgBAFQgCAGAAAGIAAA+IgdAAIAAhyIAbAAIAAATIABAAQAEgJAJgHQAKgGAMAAQALAAAIAEQAIAEAFAGQAFAHADAIQACAIAAAJIAABHg");
	this.shape_22.setTransform(1.125,20.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#14509B").s().p("AgNBWIAAhyIAcAAIAABygAgMg3QgFgGAAgHQAAgGAFgGQAFgFAHAAQAIAAAFAFQAFAFAAAHQAAAIgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape_23.setTransform(-8.6,17.425);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#14509B").s().p("AAaA6IgahQIAAAAIgZBQIgeAAIgnhzIAeAAIAZBSIAAAAIAZhSIAdAAIAaBSIAAAAIAZhSIAeAAIgpBzg");
	this.shape_24.setTransform(-20.9,20.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#14509B").s().p("AgXA5QgMgFgIgJQgJgHgFgMQgFgLAAgNQAAgNAFgLQAFgMAJgHQAIgJAMgEQALgEAMAAQANAAALAEQAMAEAIAJQAJAHAFAMQAFALAAANQAAANgFALQgFAMgJAHQgIAJgMAFQgLAEgNAAQgMAAgLgEgAgOghQgGADgEAFQgEAGgCAGQgCAHAAAGQAAAGACAHQACAGAEAGQAEAFAGADQAGAEAIAAQAJAAAGgEQAGgDAEgFQAEgGACgGQACgHAAgGQAAgGgCgHQgCgGgEgGQgEgFgGgDQgGgEgJAAQgIAAgGAEg");
	this.shape_25.setTransform(-37.325,20.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#14509B").s().p("AAYA7IAAg/IAAgKQgBgGgDgEQgCgFgEgCQgEgDgHAAQgGAAgFACQgFADgEAFQgDAEgBAFQgCAGAAAGIAAA+IgdAAIAAhyIAbAAIAAATIABAAQAEgJAJgHQAKgGAMAAQALAAAIAEQAIAEAFAGQAFAHADAIQACAIAAAJIAABHg");
	this.shape_26.setTransform(-51.075,20.075);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#14509B").s().p("AAfBVIhJhVIgBAAIAABVIgeAAIAAipIAeAAIAABKIABAAIBGhKIAoAAIhOBOIBUBbg");
	this.shape_27.setTransform(-64.8,17.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-100.3,0,200.7,90.4), null);


(lib.FRAME = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#24509B").ss(8,1,0,3).p("AuhuhIdDAAIAAdDI9DAAg");
	this.shape.setTransform(93,-93);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.FRAME, new cjs.Rectangle(-4,-190,194,194), null);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAcQgHgCgEgFIAKgJQACAEAEACQAEABADAAIADAAIADgBIADgCIABgEQAAgDgEgBIgJgDIgGgDQgDgBgCgBIgEgEQgCgDAAgEQAAgEACgEIAFgGIAIgDQAEgBADAAQAGAAAGACQAGACAEAFIgKAIQgBgDgEgCQgDgBgEAAQgDgBgDACQgCACAAADQAAADADABIAIADIAHACIAGADIAEAFQACADAAADQAAAGgCADQgCAEgEACIgHADIgJABQgGAAgGgCg");
	this.shape.setTransform(83.675,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAbQgEgCgDgCQgCgEgBgEQgCgEABgEIAAgjIAOAAIAAAeIAAAFIACAGQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQADACADgBIAFgBIAEgDIADgFIAAgGIAAgeIAPAAIAAA4IgOAAIAAgKQgCAFgFADQgEADgGAAQgGAAgEgCg");
	this.shape_1.setTransform(77.6,14.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMAtIAAgfIgBgGIgBgFIgDgDQgCgBgDAAQgDAAgDABIgEADIgDAFIAAAGIAAAfIgOAAIAAhZIAOAAIAAApIADgEIADgDIAFgCIAFgBQAGAAAEACQAEACACADQADADABAEQACAEAAAEIAAAkg");
	this.shape_2.setTransform(67.7,12.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAJAmQgFAAgEgCQgDgBgCgDQgCgDgBgEIAAgHIAAgaIgKAAIAAgMIAKAAIAAgRIANAAIAAARIAOAAIAAAMIgOAAIAAAZQAAAEABADQACACAEAAIAEAAIADgBIAAALIgFACg");
	this.shape_3.setTransform(62.075,13.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGArIAAg4IANAAIAAA4gAgGgbQgCgDAAgDQAAgDACgDQADgDADAAQAEAAACADQADACAAAEQAAADgDADQgCADgEAAQgDAAgDgDg");
	this.shape_4.setTransform(58.525,12.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANAdIgNgoIAAAAIgMAoIgPAAIgUg5IAQAAIAMAoIAAAAIAMgoIAPAAIAMAoIABAAIAMgoIAPAAIgUA5g");
	this.shape_5.setTransform(52.125,14.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAJAtIgWgdIAAAdIgOAAIAAhZIAOAAIAAA4IAVgXIATAAIgZAZIAaAfg");
	this.shape_6.setTransform(41.525,12.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AANAeIAAgfIgBgFIgCgFIgDgEQgCgCgEAAQgCAAgCACIgFADIgCAFIgBAGIAAAfIgPAAIAAg5IAPAAIAAAJQACgEAEgDQAFgEAGAAQAFAAAEACQAEACADAEQADADAAAEIABAJIAAAjg");
	this.shape_7.setTransform(34.35,13.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLAdIgHgDQgEgCgCgDQgCgDAAgGQAAgGAEgEQAEgCAFgCIANgEIANAAIAAgCQAAgFgEgDQgEgCgFAAQgEAAgEACIgHAFIgHgJQAEgEAHgDQAGgCAGAAQAIAAAFACQAFACACAEQADADABAEQACAFAAAEIAAAiIgOAAIAAgIIAAAAQgCAEgFADQgFACgFAAIgHgBgAACADIgGACIgFACQgCACAAADIABAEIACACIADABIAEAAQAGAAAEgDQAEgFAAgGIAAgDIgDAAg");
	this.shape_8.setTransform(27.375,14);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeArIAAhVIAgAAIAJABIAJAFQADACACAEQADAEAAAGQAAAHgEAFQgEAFgHACQAIABAFAEQAFAFAAAJQAAAGgCAFQgDAFgFADQgEADgGABIgLACgAgPAeIANAAIAGgBIAGgCQADgBABgCQACgDAAgEQAAgGgEgDQgFgDgIAAIgOAAgAgPgHIANAAQAHAAAEgDQAEgDAAgFQAAgGgEgDQgFgCgHAAIgMAAg");
	this.shape_9.setTransform(20.575,12.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#648C3C").ss(1,1,2).p("An9iBIP7AAQAKAAAAAKIAADvQAAAKgKAAIv7AAQgKAAAAgKIAAjvQAAgKAKAAg");
	this.shape_10.setTransform(52,13);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#14509B").s().p("An9CCQgKAAAAgKIAAjvQAAgKAKAAIP7AAQAKAAAAAKIAADvQAAAKgKAAg");
	this.shape_11.setTransform(52,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-1,-1,106,28), null);


(lib.QUOTEtype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.quote();
	this.instance.setTransform(-5.6,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.QUOTEtype, new cjs.Rectangle(-97.4,-24.8,129.4,72.2), null);


(lib.HB_logo_vert_2c = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Heritage_Vert_2c_RGBeps("synched",0);
	this.instance.setTransform(0,0,1,1,0,0,0,161.5,125.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HB_logo_vert_2c, new cjs.Rectangle(-161.5,-125.9,323.1,251.9), null);


// stage content:
(lib.HB_Display_Stanwood_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [144];
	// timeline functions:
	this.frame_144 = function() {
		if(!this.alreadyExecuted){
		this.alreadyExecuted=true;
		this.loopNum=1;
		} else {
		this.loopNum++;
		if(this.loopNum==2){
		this.stop();
		}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(144).call(this.frame_144).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,2).p("EgMVguyIYrAAQAFAAAAAYMAAABc1QAAAYgFAAI4rAAQgFAAAAgYMAAAhc1QAAgYAFAAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(145));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(80.35,426.45,0.88,0.88,0,0,0,52.1,13);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(70).to({_off:false},0).to({alpha:1},5).wait(70));

	// HEAD1
	this.instance_1 = new lib.HEAD1();
	this.instance_1.setTransform(167.45,361.95,0.8703,0.8703,0,0,0,100.5,41.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(53).to({_off:false},0).wait(92));

	// quote-type
	this.instance_2 = new lib.QUOTEtype();
	this.instance_2.setTransform(108,90.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(145));

	// quote-box
	this.instance_3 = new lib.QUOTEbox();
	this.instance_3.setTransform(-157.8,100.8,1,1.333,0,0,0,-102.7,30.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(145));

	// FRAME
	this.instance_4 = new lib.FRAME();
	this.instance_4.setTransform(220.55,185.75,0.7449,0.7449,0,0,0,93,-92.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(25).to({_off:false},0).to({x:98.25},12,cjs.Ease.quadOut).wait(108));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	var mask_graphics_14 = new cjs.Graphics().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	var mask_graphics_15 = new cjs.Graphics().p("EgMdAt4MAAAhbFIY7AAMAAABbFg");
	var mask_graphics_16 = new cjs.Graphics().p("EgMaAs6MAAAhYcIY2AAMAAABYcg");
	var mask_graphics_17 = new cjs.Graphics().p("EgMYAr7MAAAhVyIYyAAMAAABVyg");
	var mask_graphics_18 = new cjs.Graphics().p("EgMWAq8MAAAhTIIYuAAMAAABTIg");
	var mask_graphics_19 = new cjs.Graphics().p("EgMTAp+MAAAhQfIYpAAMAAABQfg");
	var mask_graphics_20 = new cjs.Graphics().p("EgMRAo/MAAAhN2IYlAAMAAABN2g");
	var mask_graphics_21 = new cjs.Graphics().p("EgMPAoAMAAAhLMIYhAAMAAABLMg");
	var mask_graphics_22 = new cjs.Graphics().p("EgMMAnBMAAAhIiIYcAAMAAABIig");
	var mask_graphics_23 = new cjs.Graphics().p("EgMKAmDMAAAhF5IYXAAMAAABF5g");
	var mask_graphics_24 = new cjs.Graphics().p("EgMIAlEMAAAhDPIYTAAMAAABDPg");
	var mask_graphics_25 = new cjs.Graphics().p("EgMFAkFMAAAhAlIYOAAMAAABAlg");
	var mask_graphics_26 = new cjs.Graphics().p("EgMDAjGMAAAg97IYKAAMAAAA97g");
	var mask_graphics_27 = new cjs.Graphics().p("EgMBAiIMAAAg7TIYGAAMAAAA7Tg");
	var mask_graphics_28 = new cjs.Graphics().p("EgL+AhJMAAAg4pIYBAAMAAAA4pg");
	var mask_graphics_29 = new cjs.Graphics().p("EgL8AgKMAAAg1/IX9AAMAAAA1/g");
	var mask_graphics_30 = new cjs.Graphics().p("Ar6fLMAAAgzVIX5AAMAAAAzVg");
	var mask_graphics_31 = new cjs.Graphics().p("Ar3eNMAAAgwsIX0AAMAAAAwsg");
	var mask_graphics_32 = new cjs.Graphics().p("Ar1dOMAAAguCIXwAAMAAAAuCg");
	var mask_graphics_33 = new cjs.Graphics().p("ArzcPMAAAgrYIXsAAMAAAArYg");
	var mask_graphics_34 = new cjs.Graphics().p("ArwbQMAAAgovIXnAAMAAAAovg");
	var mask_graphics_35 = new cjs.Graphics().p("AruaSMAAAgmGIXjAAMAAAAmGg");
	var mask_graphics_36 = new cjs.Graphics().p("ArsZTMAAAgjcIXfAAMAAAAjcg");
	var mask_graphics_37 = new cjs.Graphics().p("ArqYSMAAAggyIXaAAMAAAAgyg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:79.9997,y:299.85}).wait(14).to({graphics:mask_graphics_14,x:79.9997,y:299.85}).wait(1).to({graphics:mask_graphics_15,x:79.7936,y:293.6485}).wait(1).to({graphics:mask_graphics_16,x:79.5876,y:287.3738}).wait(1).to({graphics:mask_graphics_17,x:79.3816,y:281.0992}).wait(1).to({graphics:mask_graphics_18,x:79.1756,y:274.8246}).wait(1).to({graphics:mask_graphics_19,x:78.9695,y:268.55}).wait(1).to({graphics:mask_graphics_20,x:78.7635,y:262.2753}).wait(1).to({graphics:mask_graphics_21,x:78.5575,y:256.0007}).wait(1).to({graphics:mask_graphics_22,x:78.3514,y:249.7261}).wait(1).to({graphics:mask_graphics_23,x:78.1454,y:243.4515}).wait(1).to({graphics:mask_graphics_24,x:77.9394,y:237.1768}).wait(1).to({graphics:mask_graphics_25,x:77.7334,y:230.9022}).wait(1).to({graphics:mask_graphics_26,x:77.5273,y:224.6276}).wait(1).to({graphics:mask_graphics_27,x:77.3213,y:218.353}).wait(1).to({graphics:mask_graphics_28,x:77.1153,y:212.0783}).wait(1).to({graphics:mask_graphics_29,x:76.9092,y:205.8037}).wait(1).to({graphics:mask_graphics_30,x:76.7032,y:199.5291}).wait(1).to({graphics:mask_graphics_31,x:76.4972,y:193.2545}).wait(1).to({graphics:mask_graphics_32,x:76.2911,y:186.9798}).wait(1).to({graphics:mask_graphics_33,x:76.0851,y:180.7052}).wait(1).to({graphics:mask_graphics_34,x:75.8791,y:174.4306}).wait(1).to({graphics:mask_graphics_35,x:75.6731,y:168.156}).wait(1).to({graphics:mask_graphics_36,x:75.467,y:161.8813}).wait(1).to({graphics:mask_graphics_37,x:75.1944,y:155.4258}).wait(108));

	// PIC
	this.instance_5 = new lib.PIC();
	this.instance_5.setTransform(150,125);

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(14).to({regX:0.9,regY:0.8,scaleX:0.55,scaleY:0.55,x:130.5,y:95.45},23).wait(108));

	// LOGO
	this.instance_6 = new lib.HB_logo_vert_2c();
	this.instance_6.setTransform(80.05,514.25,0.32,0.32,0,0,0,0.3,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(145));

	// BKGD
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(145));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(24.9,299.5,268,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 24,
	color: "#333333",
	opacity: 1.00,
	manifest: [
		{src:"images/HB_Display_Stanwood_160x600_atlas_1.jpg?1605647339320", id:"HB_Display_Stanwood_160x600_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;